// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngBdg
{
    public decimal Uid { get; set; }

    public string BdgCod { get; set; }

    public decimal? EtyUid { get; set; }

    public string BdgDsc { get; set; }

    public decimal LogDel { get; set; }

    public decimal BdgTypUid { get; set; }

    public DateTime? BdgBrkTss { get; set; }

    public decimal? BrkUid { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngRes> AngRes { get; set; } = new List<AngRes>();

    public virtual AngMesBrk BrkU { get; set; }
}