// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngGrp
{
    public decimal Uid { get; set; }

    public string GrpCod { get; set; }

    public decimal? EtyUid { get; set; }

    public decimal GrpPblUsg { get; set; }

    public string GrpTyp { get; set; }

    public string GrpIco { get; set; }

    public string EmlAdd { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public decimal SchEnb { get; set; }

    public string SchTyp { get; set; }

    public string DisGrpTyp { get; set; }

    public decimal DisDayMinSl1 { get; set; }

    public decimal DisDayMinSl2 { get; set; }

    public decimal DisDayMinSl3 { get; set; }

    public decimal DisDayMinSl4 { get; set; }

    public decimal DisDayMinSl5 { get; set; }

    public decimal PerNis { get; set; }

    public decimal? CalUid { get; set; }

    public decimal? GrpEff { get; set; }

    public decimal DisDayMinSl6 { get; set; }

    public decimal DisDayMinSl7 { get; set; }

    public virtual ICollection<AngGrpLng> AngGrpLng { get; set; } = new List<AngGrpLng>();

    public virtual ICollection<AngRes> AngRes { get; set; } = new List<AngRes>();
}