// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesNotPln
{
    public decimal Uid { get; set; }

    public string NotPlnCod { get; set; }

    public decimal? EtyUid { get; set; }

    public string NotPlnIco { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public string ProCod { get; set; }

    public string CauCod { get; set; }

    public virtual ICollection<AngMesNotPlnLng> AngMesNotPlnLng { get; set; } = new List<AngMesNotPlnLng>();
}