// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesSsp
{
    public decimal Uid { get; set; }

    public string SspCod { get; set; }

    public decimal SspWrk { get; set; }

    public decimal SspMac { get; set; }

    public decimal SspBlc { get; set; }

    public decimal? EtyUid { get; set; }

    public string SspIco { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngMesSspLng> AngMesSspLng { get; set; } = new List<AngMesSspLng>();

    public virtual ICollection<MesBckEvt> MesBckEvt { get; set; } = new List<MesBckEvt>();

    public virtual ICollection<MesBckEvtOpe> MesBckEvtOpe { get; set; } = new List<MesBckEvtOpe>();

    public virtual ICollection<MesDiaOpe> MesDiaOpe { get; set; } = new List<MesDiaOpe>();

    public virtual ICollection<MesEvt> MesEvt { get; set; } = new List<MesEvt>();

    public virtual ICollection<MesEvtOpe> MesEvtOpe { get; set; } = new List<MesEvtOpe>();
}