// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesNotPlnLng
{
    public decimal RecUid { get; set; }

    public decimal LngUid { get; set; }

    public string NotPlnDsc { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public virtual AngMesNotPln RecU { get; set; }
}