// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesDecTyp
{
    public decimal Uid { get; set; }

    public string DecTypCod { get; set; }

    public string DecTypIco { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngMesDecTypLng> AngMesDecTypLng { get; set; } = new List<AngMesDecTypLng>();

    public virtual ICollection<MesBckEvtDet> MesBckEvtDet { get; set; } = new List<MesBckEvtDet>();

    public virtual ICollection<MesDiaOpeDet> MesDiaOpeDet { get; set; } = new List<MesDiaOpeDet>();

    public virtual ICollection<MesEvtDet> MesEvtDet { get; set; } = new List<MesEvtDet>();
}