// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesSts
{
    public decimal Uid { get; set; }

    public string StsCod { get; set; }

    public string StsIco { get; set; }

    public string StsClr { get; set; }

    public decimal StsWhtTxt { get; set; }

    public decimal StsAlm { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngMesStsLng> AngMesStsLng { get; set; } = new List<AngMesStsLng>();

    public virtual ICollection<MesDiaOpe> MesDiaOpe { get; set; } = new List<MesDiaOpe>();
}