// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesBrk
{
    public decimal Uid { get; set; }

    public string BrkCod { get; set; }

    public decimal? EtyUid { get; set; }

    public string BrkIco { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngBdg> AngBdg { get; set; } = new List<AngBdg>();

    public virtual ICollection<AngMesBrkLng> AngMesBrkLng { get; set; } = new List<AngMesBrkLng>();

    public virtual ICollection<MesBckEvtOpe> MesBckEvtOpe { get; set; } = new List<MesBckEvtOpe>();

    public virtual ICollection<MesEvtOpe> MesEvtOpe { get; set; } = new List<MesEvtOpe>();

    public virtual ICollection<TblResBrk> TblResBrk { get; set; } = new List<TblResBrk>();
}