// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesEvtOpeSts
{
    public decimal Uid { get; set; }

    public string EvtOpeStsCod { get; set; }

    public string EvtOpeStsIco { get; set; }

    public decimal LogDel { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? Tsd { get; set; }

    public virtual ICollection<AngMesEvtOpeStsLng> AngMesEvtOpeStsLng { get; set; } = new List<AngMesEvtOpeStsLng>();

    public virtual ICollection<MesBckEvtOpe> MesBckEvtOpe { get; set; } = new List<MesBckEvtOpe>();

    public virtual ICollection<MesEvtOpe> MesEvtOpe { get; set; } = new List<MesEvtOpe>();
}