// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class AngMesDecTypLng
{
    public decimal RecUid { get; set; }

    public decimal LngUid { get; set; }

    public string DecTypDsc { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public virtual AngMesDecTyp RecU { get; set; }
}