// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class MesDiaDefMac
{
    public decimal Uid { get; set; }

    public decimal ResUid { get; set; }

    public decimal MacUid { get; set; }

    public decimal MacSrtOrd { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public virtual AngRes MacU { get; set; }

    public virtual AngRes ResU { get; set; }
}