// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class TblResBrk
{
    public decimal Uid { get; set; }

    public decimal ResUid { get; set; }

    public decimal? EtyUid { get; set; }

    public decimal BrkUid { get; set; }

    public DateTime TssStr { get; set; }

    public DateTime? TssEnd { get; set; }

    public decimal? DtcDayUid { get; set; }

    public decimal ResLgnStrUid { get; set; }

    public decimal? ResLgnEndUid { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public DateTime? EdtTssStr { get; set; }

    public DateTime? EdtTssEnd { get; set; }

    public virtual AngMesBrk BrkU { get; set; }

    public virtual AngDay DtcDayU { get; set; }

    public virtual AngRes ResLgnEndU { get; set; }

    public virtual AngRes ResLgnStrU { get; set; }

    public virtual AngRes ResU { get; set; }
}