// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.JMES;

public partial class TblResClk
{
    public decimal Uid { get; set; }

    public decimal ResUid { get; set; }

    public DateTime? ClkInnTss { get; set; }

    public DateTime? ClkOutTss { get; set; }

    public decimal? DtcDayUid { get; set; }

    public DateTime? EdtInnTss { get; set; }

    public DateTime? EdtOutTss { get; set; }

    public decimal? EdtInnRngUid { get; set; }

    public decimal? EdtOutRngUid { get; set; }

    public DateTime? Tsi { get; set; }

    public DateTime? Tsu { get; set; }

    public decimal RecVer { get; set; }

    public decimal FlgFrcClk { get; set; }

    public decimal? KpiRngInnUid { get; set; }

    public decimal AbsClk { get; set; }

    public virtual AngDay DtcDayU { get; set; }

    public virtual AngRes ResU { get; set; }
}