// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using IMAR_DialogoOperatore.Domain.Entities.Imar_Schdulazione;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IMAR_DialogoOperatore.Infrastructure.Imar_Schedulatore;

public partial class ImarSchedulatoreContext : DbContext
{
    IConfiguration _configuration;

    public ImarSchedulatoreContext(
        DbContextOptions<ImarSchedulatoreContext> options,
        IConfiguration configuration)
        : base(options)
    {
        _configuration = configuration;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer(_configuration["ConnectionStrings:imarSchedulatore"]);
    }

    public virtual DbSet<CAL_FL_ODP> CAL_FL_ODP { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CAL_FL_ODP>(entity =>
        {
            entity.HasKey(e => new { e.GIORNO, e.ODP, e.FASE, e.SOVRACCARICO }).HasName("CAL/FL/ODP$PrimaryKey");

            entity.ToTable("CAL/FL/ODP");

            entity.HasIndex(e => e.GIORNO, "CAL/FL/ODP$CAL/FL/ODPGIORNO");

            entity.HasIndex(e => e.ODP, "CAL/FL/ODP$CAL/FL/ODPODP");

            entity.Property(e => e.GIORNO).HasColumnType("datetime");
            entity.Property(e => e.ODP).HasMaxLength(255);
            entity.Property(e => e.SOVRACCARICO).HasAnnotation("Relational:DefaultConstraintName", "DF__CAL/FL/OD__SOVRA__40058253");
            entity.Property(e => e.FLUSSO).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}