// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using IMAR_DialogoOperatore.Domain.Entities.Imar_Produzione;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IMAR_DialogoOperatore.Domain.Imar_Produzione;

public partial class ImarProduzioneContext : DbContext
{
    IConfiguration _configuration;

    public ImarProduzioneContext(
        DbContextOptions<ImarProduzioneContext> options,
            IConfiguration configuration)
        : base(options)
    {
        _configuration = configuration;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer(_configuration["ConnectionStrings:ImarProduzione"]);
    }

    public virtual DbSet<SegnalazioneDifformita> SegnalazioneDifformita { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<SegnalazioneDifformita>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Articolo)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.ArticoloEsterno)
                .HasMaxLength(45)
                .IsUnicode(false);
            entity.Property(e => e.BadgeOperatoreModifica)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.CategoriaDifformita)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Causa)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CodiceCliente)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.CodiceSegnalazione)
                .HasMaxLength(16)
                .IsUnicode(false);
            entity.Property(e => e.DataChiusura).HasColumnType("datetime");
            entity.Property(e => e.DataCreazione).HasColumnType("datetime");
            entity.Property(e => e.DataInizioGestione).HasColumnType("datetime");
            entity.Property(e => e.DataRestituzione).HasColumnType("datetime");
            entity.Property(e => e.DenominazioneCliente)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.DescrizioneArticolo)
                .HasMaxLength(80)
                .IsUnicode(false);
            entity.Property(e => e.DescrizioneDifformita).IsUnicode(false);
            entity.Property(e => e.DescrizioneFase)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FaseDifformita)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Flusso)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.InterventoRiparazione).IsUnicode(false);
            entity.Property(e => e.Link).IsUnicode(false);
            entity.Property(e => e.MisuraCorrettiva).IsUnicode(false);
            entity.Property(e => e.Odp)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.OdpRilavorazione)
                .HasMaxLength(8)
                .IsUnicode(false);
            entity.Property(e => e.OperatoreDifformita)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.OrdineVenditaContestato)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.OrigineSegnalazione)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.ReferenteInterno)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Responsabilita)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Richiedente)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.RifDocReso)
                .HasMaxLength(90)
                .IsUnicode(false);
            entity.Property(e => e.Sorgente)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Stato)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.StatoDDT)
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.StatoSegnalazione)
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.UltimaModifica).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}