// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class CAL_FL_ODP
{
    public string FLUSSO { get; set; }

    public DateTime GIORNO { get; set; }

    public string ODP { get; set; }

    public int FASE { get; set; }

    public double? T_ODP { get; set; }

    public int? RECORD { get; set; }

    public bool SOVRACCARICO { get; set; }

    public int? MANUALE { get; set; }

    public virtual FASI FASI { get; set; }
}