// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Models;

public partial class DATIMONITOR
{
    public short? GG { get; set; }

    public DateTime GIORNO { get; set; }

    public string ODP { get; set; }

    public int? QNT_RES { get; set; }

    public string ARTICOLO { get; set; }

    public string DESCRIZIONE_ARTICOLO { get; set; }

    public int FASE { get; set; }

    public string DESCRIZIONE_FASE { get; set; }

    public decimal? T_ATT_FASE { get; set; }

    public decimal? T_LAV { get; set; }

    public int? FU { get; set; }

    public string DISPONIBILE { get; set; }

    public string FLUSSO { get; set; }

    public short? IO { get; set; }

    public string NOTE_GEN { get; set; }

    public string FASE_PREC { get; set; }

    public string FLUSSO_PREC { get; set; }

    public string STATO { get; set; }

    public int? PERCAVSTO { get; set; }

    public decimal? TEMPO_STO { get; set; }

    public string CDOPERAT { get; set; }

    public string PRIORITA { get; set; }

    public string FLUSSO_SUC { get; set; }

    public DateTime DATA_RIFERIMENTO { get; set; }

    public string MATERIALE { get; set; }

    public int? ORDINAMENTO { get; set; }

    public string INFO { get; set; }

    public DateTime? GIORNO_CONSEGNA { get; set; }

    public string NOTE { get; set; }

    public string ORDINAMENTO_MANUALE { get; set; }
}