// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class DESCRIZIONE_FASI
{
    public string CODICE_FASE { get; set; }

    public string DESCRIZIONE { get; set; }

    public string CODICE_MACCHINA { get; set; }

    public short? TEMPI_ATTRAVERSAMENTO { get; set; }

    public int? P { get; set; }

    public short? TEMPI_ATTRAVERSAMENTO1 { get; set; }
}