// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class FASI
{
    public int SEQUENZA { get; set; }

    public string ORDINE_PRODUZIONE_ODP { get; set; }

    public string CODICE_FASE { get; set; }

    public double? T_ATT_FASE { get; set; }

    public double? T_LAV_FASE { get; set; }

    public string FLUSSO { get; set; }

    public string OPERATORE { get; set; }

    public bool? FISSO { get; set; }

    public DateTime? DATA_MIN { get; set; }

    public DateTime? DATA_MAX { get; set; }

    public bool? I_O { get; set; }

    public double? NUOVO_TEMPO { get; set; }

    public int? PCAVANZ { get; set; }

    public DateTime? DATA_ARRIVO_MATE { get; set; }

    public int? QUANTITA_RES_FASE { get; set; }

    public string URGENTE { get; set; }

    public string DATA_MAT_UPDATER { get; set; }

    public virtual ICollection<CAL_FL_ODP> CAL_FL_ODP { get; set; } = new List<CAL_FL_ODP>();
}