// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class FASIINFLUSSO
{
    public string FLUSSO { get; set; }

    public string CODICE_FASE { get; set; }

    public virtual DESCRIZIONE_FASI CODICE_FASENavigation { get; set; }
}