// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class ODC_ODP
{
    public string ORDINE_RIGA { get; set; }

    public string ODP { get; set; }

    public int? LIVELLO { get; set; }

    public virtual ORDINE_PRODUZIONE ODPNavigation { get; set; }

    public virtual ORDINE_CLIENTE ORDINE_RIGANavigation { get; set; }
}