// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class ORDINE_PRODUZIONE
{
    public string ODP { get; set; }

    public string ARTICOLO { get; set; }

    public string STATO_ODP { get; set; }

    public int? QUANTITA_RESIDUA { get; set; }

    public double? T_RES_ODP { get; set; }

    public string ELABORATO { get; set; }

    public string SALDATO { get; set; }

    public DateTime? DATA_ARRIVO_MAT { get; set; }

    public string DATA_FINE { get; set; }

    public virtual ICollection<ODC_ODP> ODC_ODP { get; set; } = new List<ODC_ODP>();
}