// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Schedulazione;

public partial class ORDINE_CLIENTE
{
    public string ORDINE_RIGA { get; set; }

    public string CODICE_CLIENTE { get; set; }

    public string TIPO_MOVIMENTO { get; set; }

    public int? QUANTITA_ORDINE { get; set; }

    public DateTime? DATA_CONSEGNA { get; set; }

    public double? T_RES_ODC { get; set; }

    public DateTime? DATA_INSERIMENTO { get; set; }

    public DateTime? DATA_UPDATE { get; set; }

    public int? FATTORE_URG { get; set; }

    public string SALDATO { get; set; }

    public DateTime? DATA_FINE { get; set; }

    public virtual ICollection<ODC_ODP> ODC_ODP { get; set; } = new List<ODC_ODP>();
}