namespace IMAR_DialogoOperatore.Domain.Models
{
    public class mesDiaOpe
    {
        public double ID_ResLgn6708 { get; set; }
        public bool ID_DecTyp3295 { get; set; }
        public int ID_DecTyp3298 { get; set; }
        public string ID_DecTyp3292 { get; set; }
        public int ID_DecTyp3291 { get; set; }
        public string ID_DecTyp3293 { get; set; }
        public int ID_Det3797 { get; set; }
        public int ID_ResPri2531 { get; set; }
        public decimal ID_Det6696 { get; set; }
        public int ID_DecTyp3305 { get; set; }
        public string ID_Det6684 { get; set; }
        public string ID_Det6686 { get; set; }
        public int ID_ResLgn3917 { get; set; }
        public bool ID_ResLgn3915 { get; set; }
        public bool ID_ResLgn3914 { get; set; }
        public double ID_ResPri6708 { get; set; }
        public string ID_Det6595 { get; set; }
        public string ID_Det6594 { get; set; }
        public string ID_Det6593 { get; set; }
        public string ID_Det6592 { get; set; }
        public string ID_Det6591 { get; set; }
        public string ID_Det6590 { get; set; }
        public string ID_Det6585 { get; set; }
        public string ID_Det6584 { get; set; }
        public string ID_Det6583 { get; set; }
        public string ID_Det6582 { get; set; }
        public string ID_Det6589 { get; set; }
        public string ID_Det6588 { get; set; }
        public string ID_Det6587 { get; set; }
        public string ID_Det6586 { get; set; }
        public string ID_Det6581 { get; set; }
        public double ID_Det3384 { get; set; }
        public int ID_Det3386 { get; set; }
        public decimal ID_Det3380 { get; set; }
        public string ID_ResPri371 { get; set; }
        public string ID_ResPri372 { get; set; }
        public bool ID_ResPri375 { get; set; }
        public bool ID_ResPri373 { get; set; }
        public string ID_ResPri374 { get; set; }
        public string ID_ResLgn368 { get; set; }
        public int ID_ResLgn367 { get; set; }
        public double ID_ResPri3931 { get; set; }
        public int ID_ResLgn365 { get; set; }
        public decimal ID_Det3372 { get; set; }
        public decimal ID_Det3373 { get; set; }
        public string ID_Det3370 { get; set; }
        public decimal ID_Det3371 { get; set; }
        public decimal ID_Det3376 { get; set; }
        public decimal ID_Det3377 { get; set; }
        public decimal ID_Det3374 { get; set; }
        public decimal ID_Det3375 { get; set; }
        public int ID_ResPri382 { get; set; }
        public double ID_ResPri380 { get; set; }
        public decimal ID_Det3378 { get; set; }
        public decimal ID_Det3379 { get; set; }
        public double ID_ResLgn3931 { get; set; }
        public int ID_ResPri3917 { get; set; }
        public bool ID_ResPri3914 { get; set; }
        public bool ID_ResPri3915 { get; set; }
        public bool ID_ResLgn5325 { get; set; }
        public bool ID_ResLgn5326 { get; set; }
        public bool ID_ResLgn5324 { get; set; }
        public double ID_ResPri365 { get; set; }
        public string ID_ResPri368 { get; set; }
        public string ID_ResLgn3938 { get; set; }
        public int ID_ResPri367 { get; set; }
        public int ID_ResLgn2544 { get; set; }
        public int ID_Sts3138 { get; set; }
        public string ID_Sts3131 { get; set; }
        public double ID_Det3347 { get; set; }
        public string ID_Sts3132 { get; set; }
        public double ID_Det3348 { get; set; }
        public string ID_Sts3130 { get; set; }
        public bool ID_Sts3135 { get; set; }
        public double ID_Sts3136 { get; set; }
        public bool ID_Sts3133 { get; set; }
        public int ID_Det3349 { get; set; }
        public bool ID_Sts3134 { get; set; }
        public int ID_Sts3128 { get; set; }
        public string ID_Sts3129 { get; set; }
        public double ID_Evt3240 { get; set; }
        public double ID_Evt3241 { get; set; }
        public double ID_Evt3245 { get; set; }
        public int ID_Evt3242 { get; set; }
        public int ID_Evt3243 { get; set; }
        public int ID_Dia3271 { get; set; }
        public int ID_Dia3270 { get; set; }
        public double ID_Dia3275 { get; set; }
        public double ID_Dia3274 { get; set; }
        public int ID_Dia3276 { get; set; }
        public double ID_Evt3251 { get; set; }
        public double ID_Evt3253 { get; set; }
        public bool ID_Evt3254 { get; set; }
        public int ID_ResLgn382 { get; set; }
        public double ID_ResLgn380 { get; set; }
        public double ID_ResLgn381 { get; set; }
        public string ID_Evt3247 { get; set; }
        public string ID_Det3369 { get; set; }
        public string ID_Det3350 { get; set; }
        public int ID_ResLgn2531 { get; set; }
        public string ID_Det3354 { get; set; }
        public string ID_Det3355 { get; set; }
        public double ID_Dia3266 { get; set; }
        public bool ID_Det3352 { get; set; }
        public string ID_Det3353 { get; set; }
        public bool ID_Dia3268 { get; set; }
        public double ID_Evt3262 { get; set; }
        public double ID_Dia3267 { get; set; }
        public double ID_Evt3263 { get; set; }
        public double ID_Dia3269 { get; set; }
        public bool ID_Evt3261 { get; set; }
        public int ID_Evt3265 { get; set; }
        public string ID_ResLgn371 { get; set; }
        public bool ID_Evt3258 { get; set; }
        public bool ID_ResPri5324 { get; set; }
        public string ID_ResLgn379 { get; set; }
        public string ID_Det3358 { get; set; }
        public string ID_Det3359 { get; set; }
        public string ID_Det3356 { get; set; }
        public string ID_ResLgn378 { get; set; }
        public bool ID_ResLgn375 { get; set; }
        public string ID_ResLgn376 { get; set; }
        public bool ID_ResPri5326 { get; set; }
        public bool ID_ResLgn373 { get; set; }
        public int ID_Sts3145 { get; set; }
        public bool ID_ResPri5325 { get; set; }
        public string ID_ResLgn374 { get; set; }
    }
}
