namespace IMAR_DialogoOperatore.Domain.Models
{
    public class mesRcpActOpe
    {
        public string ID_EvtOpe3282 { get; set; }
        public double ID_EvtDetLst3344 { get; set; }
        public int ID_EvtDetLst3346 { get; set; }
        public decimal ID_EvtDetLst3340 { get; set; }
        public decimal ID_EvtDetLst3342 { get; set; }
        public double ID_EvtOpe3277 { get; set; }
        public double ID_EvtOpe3278 { get; set; }
        public double ID_EvtOpe3279 { get; set; }
        public int ID_EvtOpe3290 { get; set; }
        public bool ID_ResPri6232 { get; set; }
        public double ID_EvtOpe3288 { get; set; }
        public int ID_EvtOpe3284 { get; set; }
        public int ID_ResPri2531 { get; set; }
        public double ID_EvtDetLst3306 { get; set; }
        public bool ID_Evt9973 { get; set; }
        public string ID_EvtDetLst3315 { get; set; }
        public string ID_EvtDetLst3314 { get; set; }
        public bool ID_Evt9980 { get; set; }
        public string ID_EvtDetLst3317 { get; set; }
        public bool ID_EvtDetLst3311 { get; set; }
        public string ID_EvtDetLst3313 { get; set; }
        public string ID_EvtDetLst3312 { get; set; }
        public int ID_EvtDetLst3793 { get; set; }
        public bool ID_Evt9979 { get; set; }
        public int ID_EvtDetLst3308 { get; set; }
        public double ID_EvtDetLst3307 { get; set; }
        public string ID_EvtDetLst3309 { get; set; }
        public int ID_ResPri6708 { get; set; }
        public string ID_EvtDetLst3328 { get; set; }
        public double ID_EvtOpeDetLst3422 { get; set; }
        public double ID_EvtOpeDetLst3423 { get; set; }
        public double ID_EvtOpeDetLst3424 { get; set; }
        public string ID_EvtDetLst3318 { get; set; }
        public decimal ID_EvtDetLst3337 { get; set; }
        public decimal ID_EvtDetLst3336 { get; set; }
        public decimal ID_EvtDetLst3339 { get; set; }
        public decimal ID_EvtDetLst3338 { get; set; }
        public decimal ID_EvtDetLst3333 { get; set; }
        public decimal ID_EvtDetLst3332 { get; set; }
        public decimal ID_EvtDetLst3335 { get; set; }
        public decimal ID_EvtDetLst3334 { get; set; }
        public decimal ID_EvtDetLst3331 { get; set; }
        public int ID_EvtOpeDetLst3434 { get; set; }
        public string ID_EvtDetLst3329 { get; set; }
        public decimal ID_EvtDetLst6697 { get; set; }
        public string ID_ResPri371 { get; set; }
        public string ID_ResPri372 { get; set; }
        public int ID_EvtDet3346 { get; set; }
        public bool ID_ResPri375 { get; set; }
        public bool ID_ResPri373 { get; set; }
        public string ID_ResPri374 { get; set; }
        public double ID_ResPri3931 { get; set; }
        public int ID_ResPri382 { get; set; }
        public double ID_ResPri380 { get; set; }
        public bool ID_EvtTyp3229 { get; set; }
        public string ID_EvtTyp3227 { get; set; }
        public string ID_EvtTyp3228 { get; set; }
        public int ID_ResPri3917 { get; set; }
        public bool ID_ResPri3914 { get; set; }
        public bool ID_ResPri3915 { get; set; }
        public int ID_EvtTyp3225 { get; set; }
        public string ID_EvtTyp3226 { get; set; }
        public int ID_EvtTyp3239 { get; set; }
        public bool ID_Evt9957 { get; set; }
        public double ID_ResPri365 { get; set; }
        public string ID_ResPri368 { get; set; }
        public int ID_EvtTyp3232 { get; set; }
        public double ID_EvtTyp3230 { get; set; }
        public int ID_ResPri367 { get; set; }
        public string ID_EvtDetLst6536 { get; set; }
        public decimal ID_ResPri5351 { get; set; }
        public decimal ID_ResPri5350 { get; set; }
        public string ID_EvtDet3309 { get; set; }
        public int ID_EvtDet3308 { get; set; }
        public double ID_EvtDet3307 { get; set; }
        public double ID_EvtDet3306 { get; set; }
        public double ID_Evt3240 { get; set; }
        public double ID_Evt3241 { get; set; }
        public string ID_EvtDetLst6663 { get; set; }
        public double ID_Evt3245 { get; set; }
        public int ID_Evt3242 { get; set; }
        public int ID_Evt3243 { get; set; }
        public string ID_EvtDetLst6559 { get; set; }
        public string ID_EvtDetLst6558 { get; set; }
        public string ID_EvtDetLst6557 { get; set; }
        public string ID_EvtDetLst6556 { get; set; }
        public string ID_EvtDetLst6555 { get; set; }
        public double ID_Evt3251 { get; set; }
        public string ID_EvtDetLst6554 { get; set; }
        public string ID_EvtDetLst6553 { get; set; }
        public string ID_EvtDetLst6674 { get; set; }
        public string ID_EvtDetLst6552 { get; set; }
        public string ID_EvtDetLst6551 { get; set; }
        public double ID_Evt3253 { get; set; }
        public bool ID_Evt3254 { get; set; }
        public string ID_Evt3247 { get; set; }
        public decimal ID_EvtDetLst6689 { get; set; }
        public decimal ID_EvtDetLst6688 { get; set; }
        public double ID_Evt3262 { get; set; }
        public string ID_EvtDetLst6565 { get; set; }
        public double ID_Evt3263 { get; set; }
        public string ID_EvtDetLst6564 { get; set; }
        public string ID_EvtDetLst6563 { get; set; }
        public bool ID_Evt3261 { get; set; }
        public string ID_EvtDetLst6562 { get; set; }
        public string ID_EvtDetLst6561 { get; set; }
        public string ID_EvtDetLst6560 { get; set; }
        public string ID_EvtDetLst6681 { get; set; }
        public int ID_Evt3265 { get; set; }
        public bool ID_Evt3258 { get; set; }
        public bool ID_ResPri5324 { get; set; }
        public bool ID_ResPri5326 { get; set; }
        public bool ID_ResPri5325 { get; set; }
    }
}
