namespace IMAR_DialogoOperatore.Domain.Models
{
    public class vrtManNotActive
    {
        public bool USA_QTY_2 { get; set; }
        public string cusDsc { get; set; }
        public decimal effAvg { get; set; }
        public string itmCod { get; set; }
        public string itmDsc { get; set; }
        public string itmIndMod { get; set; }
        public string itmUid { get; set; }
        public string itmUniMeaBasCod { get; set; }
        public string itmUniMeaBasDsc { get; set; }
        public string itmUniMeaBasUid { get; set; }
        public string jobOrdCod { get; set; }
        public string jobOrdDsc { get; set; }
        public string jobOrdUid { get; set; }
        public string macCod { get; set; }
        public string macUid { get; set; }
        public double nmvQt2Nco { get; set; }
        public double nmvQt2Prd { get; set; }
        public double nmvQt2Rej { get; set; }
        public double nmvQtyNco { get; set; }
        public double nmvQtyPrd { get; set; }
        public double nmvQtyRej { get; set; }
        public string notCod { get; set; }
        public string notSts { get; set; }
        public string phsNotPln { get; set; }
        public string prdCycCod { get; set; }
        public string prdCycDsc { get; set; }
        public string prdCycUid { get; set; }
        public string prdOrdCod { get; set; }
        public double prdOrdQt2 { get; set; }
        public decimal prdOrdQty { get; set; }
        public string prdOrdUid { get; set; }
        public string prdPhsCod { get; set; }
        public string prdPhsDsc { get; set; }
        public string prdPhsUid { get; set; }
        public string proCod { get; set; }
        public string prsFldClr001 { get; set; }
        public string prsFldClr002 { get; set; }
        public string prsFldClr003 { get; set; }
        public string prsFldClr004 { get; set; }
        public string prsFldClr005 { get; set; }
        public string prsFldClr006 { get; set; }
        public string prsFldClr007 { get; set; }
        public string prsFldClr008 { get; set; }
        public string prsFldClr009 { get; set; }
        public string prsFldClr010 { get; set; }
        public string prsFldIco001 { get; set; }
        public string prsFldIco002 { get; set; }
        public string prsFldIco003 { get; set; }
        public string prsFldIco004 { get; set; }
        public string prsFldIco005 { get; set; }
        public int prtNum { get; set; }
        public double qt2Cof { get; set; }
        public double qt2Nco { get; set; }
        public double qt2Prd { get; set; }
        public double qt2Rej { get; set; }
        public decimal qtyNco { get; set; }
        public decimal qtyPrd { get; set; }
        public decimal qtyRej { get; set; }
        public string resCod { get; set; }
        public string subJobOrdCod { get; set; }
        public string subJobOrdDsc { get; set; }
        public string subJobOrdUid { get; set; }
        public decimal totWrkTim { get; set; }
        public string tssDue { get; set; }
        public string tssStrPrd { get; set; }
        public string uid { get; set; }
        public string wrcCod { get; set; }
        public string wrcUid { get; set; }
        public string wrhCod { get; set; }
        public string wrhUid { get; set; }
        public decimal wrkTimOpe { get; set; }
    }
}
