// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Produzione;

public partial class Forzatura
{
    public Guid Id { get; set; }

    public string RigaOrdine { get; set; }

    public DateTime DataFineLavori { get; set; }

    public string OreAllocazioneGiornaliera { get; set; }

    public string Utente { get; set; }

    public DateTime CreationTime { get; set; }

    public bool Attiva { get; set; }

    public virtual ICollection<OrdineProduzioneForzato> OrdineProduzioneForzato { get; set; } = new List<OrdineProduzioneForzato>();
}