// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Produzione;

public partial class OrdineProduzioneForzato
{
    public Guid Id { get; set; }

    public string OrdineProduzione { get; set; }

    public string Flusso { get; set; }

    public DateTime Giorno { get; set; }

    public int Fase { get; set; }

    public double Durata { get; set; }

    public string Action { get; set; }

    public DateTime CreationDate { get; set; }

    public Guid ForzaturaId { get; set; }

    public DateTime? RejectDate { get; set; }

    public DateTime? RejectTo { get; set; }

    public string CodiceFase { get; set; }

    public DateTime? DataArrivoMateriale { get; set; }

    public string DescrizioneFase { get; set; }

    public bool InFlusso { get; set; }

    public int Livello { get; set; }

    public virtual Forzatura Forzatura { get; set; }
}