// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Domain.Entities.Imar_Produzione;

public partial class SegnalazioneDifformita
{
    public Guid Id { get; set; }

    public DateTime? DataChiusura { get; set; }

    public DateTime? DataCreazione { get; set; }

    public string Richiedente { get; set; }

    public string Flusso { get; set; }

    public string FaseDifformita { get; set; }

    public string DescrizioneFase { get; set; }

    public string Odp { get; set; }

    public string Articolo { get; set; }

    public string ArticoloEsterno { get; set; }

    public string DescrizioneArticolo { get; set; }

    public double? QtaProdotta { get; set; }

    public double? QtaDifforme { get; set; }

    public double? CostoGestioneDifformita { get; set; }

    public double? CostoLavorazione { get; set; }

    public double? CostoUnitarioMateriale { get; set; }

    public double? CostoAddebitiAccrediti { get; set; }

    public double? CostoRilavorazione { get; set; }

    public double? CostoTrasporto { get; set; }

    public string DescrizioneDifformita { get; set; }

    public string CategoriaDifformita { get; set; }

    public string MisuraCorrettiva { get; set; }

    public string InterventoRiparazione { get; set; }

    public string Link { get; set; }

    public double? PotenzialeCostoReclamo { get; set; }

    public double? NumeroControllo { get; set; }

    public double? QtaDifformiRecuperati { get; set; }

    public string Responsabilita { get; set; }

    public string OperatoreDifformita { get; set; }

    public DateTime? DataInizioGestione { get; set; }

    public string ReferenteInterno { get; set; }

    public double? TempoGestione { get; set; }

    public string CodiceCliente { get; set; }

    public string DenominazioneCliente { get; set; }

    public string RifDocReso { get; set; }

    public string Stato { get; set; }

    public double? QtaRestituita { get; set; }

    public DateTime? DataRestituzione { get; set; }

    public string StatoDDT { get; set; }

    public string OrdineVenditaContestato { get; set; }

    public string OdpRilavorazione { get; set; }

    public string OrigineSegnalazione { get; set; }

    public string StatoSegnalazione { get; set; }

    public DateTime? UltimaModifica { get; set; }

    public string BadgeOperatoreModifica { get; set; }

    public string CodiceSegnalazione { get; set; }

    public string Sorgente { get; set; }

    public int? NumeroAllegati { get; set; }

    public Guid? IdSegnalazioneDifformitaPadre { get; set; }

    public string Causa { get; set; }
}