// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IMAR_DialogoOperatore.Domain.Entities.Imar_Connect;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;

namespace IMAR_DialogoOperatore.Infrastructure.Imar_Connect;

public partial class ImarConnectContext : DbContext
{
    IConfiguration _configuration;

    public ImarConnectContext(
        DbContextOptions<ImarConnectContext> options,
            IConfiguration configuration)
        : base(options)
    {
        _configuration = configuration;
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        base.OnConfiguring(optionsBuilder);
        optionsBuilder.UseSqlServer(_configuration["ConnectionStrings:ImarConnect"]);
    }

    public virtual DbSet<Interfaccia> Interfaccia { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Interfaccia>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("Interfaccia_PK");

            entity.ToTable(tb => tb.HasTrigger("trg_InterfacciaToInterfacciaShadow"));

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.BadgeOperatore)
                .HasMaxLength(4)
                .IsUnicode(false);
            entity.Property(e => e.Bolla)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.CodiceAttivitaJMes)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.TimestampEnd).HasColumnType("datetime");
            entity.Property(e => e.TimestampStart).HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}