// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IMAR_DialogoOperatore.Domain.Entities.JMES;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace IMAR_DialogoOperatore.Domain.JMes;

public partial class SynergyJmesContext : DbContext
{
	IConfiguration _configuration;

	public SynergyJmesContext(
        DbContextOptions<SynergyJmesContext> options,
			IConfiguration configuration)
        : base(options)
	{
		_configuration = configuration;
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		base.OnConfiguring(optionsBuilder);
		optionsBuilder.UseSqlServer(_configuration["ConnectionStrings:SynergyJmesCrescenzi"]);
	}

	public virtual DbSet<AngBdg> AngBdg { get; set; }

    public virtual DbSet<AngDay> AngDay { get; set; }

    public virtual DbSet<AngGrp> AngGrp { get; set; }

    public virtual DbSet<AngGrpLng> AngGrpLng { get; set; }

    public virtual DbSet<AngMesBrk> AngMesBrk { get; set; }

    public virtual DbSet<AngMesBrkLng> AngMesBrkLng { get; set; }

    public virtual DbSet<AngMesDecTyp> AngMesDecTyp { get; set; }

    public virtual DbSet<AngMesDecTypLng> AngMesDecTypLng { get; set; }

    public virtual DbSet<AngMesEvtOpeSts> AngMesEvtOpeSts { get; set; }

    public virtual DbSet<AngMesEvtOpeStsLng> AngMesEvtOpeStsLng { get; set; }

    public virtual DbSet<AngMesSsp> AngMesSsp { get; set; }

    public virtual DbSet<AngMesSspLng> AngMesSspLng { get; set; }

    public virtual DbSet<AngMesSts> AngMesSts { get; set; }

    public virtual DbSet<AngMesStsLng> AngMesStsLng { get; set; }

    public virtual DbSet<AngRes> AngRes { get; set; }

    public virtual DbSet<MesBckEvt> MesBckEvt { get; set; }

    public virtual DbSet<MesBckEvtDet> MesBckEvtDet { get; set; }

    public virtual DbSet<MesBckEvtMacDet> MesBckEvtMacDet { get; set; }

    public virtual DbSet<MesBckEvtOpe> MesBckEvtOpe { get; set; }

    public virtual DbSet<MesDiaDefMac> MesDiaDefMac { get; set; }

    public virtual DbSet<MesDiaOpe> MesDiaOpe { get; set; }

    public virtual DbSet<MesDiaOpeDet> MesDiaOpeDet { get; set; }

    public virtual DbSet<MesEvt> MesEvt { get; set; }

    public virtual DbSet<MesEvtDet> MesEvtDet { get; set; }

    public virtual DbSet<MesEvtMacDet> MesEvtMacDet { get; set; }

    public virtual DbSet<MesEvtOpe> MesEvtOpe { get; set; }

    public virtual DbSet<TblMesClkRes> TblMesClkRes { get; set; }

    public virtual DbSet<TblResBrk> TblResBrk { get; set; }

    public virtual DbSet<TblResClk> TblResClk { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<AngBdg>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngBdg__C5B69A4A38B18A9A");

            entity.HasIndex(e => e.BdgCod, "IDXCODE234");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BdgBrkTss).HasColumnType("datetime");
            entity.Property(e => e.BdgCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.BdgDsc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.BdgTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.BrkU).WithMany(p => p.AngBdg)
                .HasForeignKey(d => d.BrkUid)
                .HasConstraintName("FRes00015");
        });

        modelBuilder.Entity<AngDay>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngDay__C5B69A4AE41462E4");

            entity.HasIndex(e => e.DayCod, "IDXCODE17");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DayCod).HasColumnType("datetime");
            entity.Property(e => e.DayWee).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Mon).HasColumnType("decimal(2, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
            entity.Property(e => e.Wee).HasColumnType("decimal(2, 0)");
            entity.Property(e => e.YeaMon).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.YeaWee).HasColumnType("decimal(4, 0)");
        });

        modelBuilder.Entity<AngGrp>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngGrp__C5B69A4A23FB07DB");

            entity.HasIndex(e => e.GrpCod, "IDXCODE42");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CalUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DisDayMinSl1).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl2).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl3).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl4).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl5).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl6).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisDayMinSl7).HasColumnType("decimal(6, 0)");
            entity.Property(e => e.DisGrpTyp)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.EmlAdd).HasMaxLength(50);
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GrpCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.GrpEff).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.GrpIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.GrpPblUsg).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.GrpTyp)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.PerNis).HasColumnType("decimal(2, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.SchEnb).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.SchTyp)
                .IsRequired()
                .HasMaxLength(1);
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngGrpLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngGrpLn__6CB1DB0B7DC8ABE6");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GrpDsc).HasMaxLength(100);
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngGrpLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00015");
        });

        modelBuilder.Entity<AngMesBrk>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngMesBr__C5B69A4A4F40662B");

            entity.HasIndex(e => e.BrkCod, "IDXCODE239");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.BrkIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngMesBrkLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngMesBr__6CB1DB0BBEC34FB3");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkDsc).HasMaxLength(100);
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngMesBrkLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00099");
        });

        modelBuilder.Entity<AngMesDecTyp>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngMesDe__C5B69A4A7651F8AD");

            entity.HasIndex(e => e.DecTypCod, "IDXCODE312");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DecTypCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.DecTypIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngMesDecTypLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngMesDe__6CB1DB0B4E7D4995");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DecTypDsc).HasMaxLength(100);
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngMesDecTypLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00125");
        });

        modelBuilder.Entity<AngMesEvtOpeSts>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngMesEv__C5B69A4A7A17B781");

            entity.HasIndex(e => e.EvtOpeStsCod, "IDXCODE316");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtOpeStsCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.EvtOpeStsIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngMesEvtOpeStsLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngMesEv__6CB1DB0BBA9B3EA4");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtOpeStsDsc).HasMaxLength(100);
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngMesEvtOpeStsLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00127");
        });

        modelBuilder.Entity<AngMesSsp>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngMesSs__C5B69A4AC49FE3AD");

            entity.HasIndex(e => e.SspCod, "IDXCODE241");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.SspBlc).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.SspCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.SspIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.SspMac).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.SspWrk).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngMesSspLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngMesSs__6CB1DB0BB03B4B21");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.SspDsc).HasMaxLength(100);
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngMesSspLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00101");
        });

        modelBuilder.Entity<AngMesSts>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngMesSt__C5B69A4A9147F7D8");

            entity.HasIndex(e => e.StsCod, "IDXCODE297");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.StsAlm).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.StsClr)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.StsCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.StsIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StsWhtTxt).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
        });

        modelBuilder.Entity<AngMesStsLng>(entity =>
        {
            entity.HasKey(e => new { e.RecUid, e.LngUid }).HasName("PK__AngMesSt__6CB1DB0BE51813D8");

            entity.Property(e => e.RecUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.StsDsc).HasMaxLength(100);
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.RecU).WithMany(p => p.AngMesStsLng)
                .HasForeignKey(d => d.RecUid)
                .HasConstraintName("FLng00117");
        });

        modelBuilder.Entity<AngRes>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__AngRes__C5B69A4AD7E63F2E");

            entity.HasIndex(e => e.ResCod, "IDXCODE40");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BdgSecSty).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.BdgUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CalUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DefWrkTmDcl).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DiaMnoCfgUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DiaOpeCfgUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DiaOpeThmUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DiaOpeViwUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DteVal).HasColumnType("datetime");
            entity.Property(e => e.DtsVal).HasColumnType("datetime");
            entity.Property(e => e.EmlAdd).HasMaxLength(50);
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntCfgDefMdlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntCfgDefPrjUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntMltPrjCfgDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntMltPrjFltDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntSchPtfCfgDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntSchPtfCmpCfgDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntSchPtfCmpFltDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.GntSchPtfFltDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LgnCrpPwd).HasMaxLength(200);
            entity.Property(e => e.LgnIpa).HasMaxLength(50);
            entity.Property(e => e.LgnUsr).HasMaxLength(100);
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MaxHouDayCons).HasColumnType("decimal(4, 2)");
            entity.Property(e => e.OrgComEdtGlb).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.OrgComFlt).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.OrgComShwGlb).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.OrgComUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.OrgGntCfgDefMdlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.OrgGntCfgDefPrjUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.PerNis).HasColumnType("decimal(2, 0)");
            entity.Property(e => e.PlnQty).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.PrjBdgSec).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.PrlGrp).HasMaxLength(100);
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.RepGrpUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.ResDsc)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ResEff).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.ResIco)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ResNam).HasMaxLength(100);
            entity.Property(e => e.ResShtDsc).HasMaxLength(50);
            entity.Property(e => e.ResSur).HasMaxLength(100);
            entity.Property(e => e.ResTpl).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.ResTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SchEnb).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.SchFin).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.SdeBarViw).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.StdWrkTim).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.TeaPlnCfgDefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.TimZonUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.TmuIco).HasMaxLength(50);
            entity.Property(e => e.TmuVal).HasColumnType("decimal(3, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
            entity.Property(e => e.UsrFavLngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.WbsGntCfgDefMdlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.WbsGntCfgDefPrjUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.WrkTimCofTol).HasColumnType("decimal(17, 4)");

            entity.HasOne(d => d.Bd).WithMany(p => p.AngRes)
                .HasForeignKey(d => d.BdgUid)
                .HasConstraintName("FRes00010");

            entity.HasOne(d => d.RepGrpU).WithMany(p => p.AngRes)
                .HasForeignKey(d => d.RepGrpUid)
                .HasConstraintName("FRes00055");
        });

        modelBuilder.Entity<MesBckEvt>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesBckEv__C5B69A4ACDC0CA66");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CnlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DtcDayUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtAnmUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtChk).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.EvtPerEff).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.EvtRefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUac).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MatDecLck).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MatFlg).HasMaxLength(20);
            entity.Property(e => e.OrgLvlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.OvrLapNum).HasColumnType("decimal(20, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResEffEndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResEffStrUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResLgnEndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResLgnStrUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResOrgUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResPriUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SspUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.TssCnsQty).HasColumnType("datetime");
            entity.Property(e => e.TssCnsTim).HasColumnType("datetime");
            entity.Property(e => e.TssEnd).HasColumnType("datetime");
            entity.Property(e => e.TssStr).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.DtcDayU).WithMany(p => p.MesBckEvt)
                .HasForeignKey(d => d.DtcDayUid)
                .HasConstraintName("FMes00072");

            entity.HasOne(d => d.ResEffEndU).WithMany(p => p.MesBckEvtResEffEndU)
                .HasForeignKey(d => d.ResEffEndUid)
                .HasConstraintName("FMes00057");

            entity.HasOne(d => d.ResEffStrU).WithMany(p => p.MesBckEvtResEffStrU)
                .HasForeignKey(d => d.ResEffStrUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00056");

            entity.HasOne(d => d.ResLgnEndU).WithMany(p => p.MesBckEvtResLgnEndU)
                .HasForeignKey(d => d.ResLgnEndUid)
                .HasConstraintName("FMes00055");

            entity.HasOne(d => d.ResLgnStrU).WithMany(p => p.MesBckEvtResLgnStrU)
                .HasForeignKey(d => d.ResLgnStrUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00054");

            entity.HasOne(d => d.ResOr).WithMany(p => p.MesBckEvtResOr)
                .HasForeignKey(d => d.ResOrgUid)
                .HasConstraintName("FMes00074");

            entity.HasOne(d => d.ResPriU).WithMany(p => p.MesBckEvtResPriU)
                .HasForeignKey(d => d.ResPriUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00052");

            entity.HasOne(d => d.SspU).WithMany(p => p.MesBckEvt)
                .HasForeignKey(d => d.SspUid)
                .HasConstraintName("FMes00070");
        });

        modelBuilder.Entity<MesBckEvtDet>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesBckEv__C5B69A4A63916037");

            entity.HasIndex(e => new { e.EvtUid, e.DecTypUid, e.DocCod }, "IDXCODE326");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CauCod).HasMaxLength(30);
            entity.Property(e => e.CusCod).HasMaxLength(30);
            entity.Property(e => e.CusDsc).HasMaxLength(100);
            entity.Property(e => e.DecTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DocCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.DocPri).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DptCod).HasMaxLength(30);
            entity.Property(e => e.DrwCod).HasMaxLength(20);
            entity.Property(e => e.EqpCod).HasMaxLength(20);
            entity.Property(e => e.EvtDetRefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ExtCod).HasMaxLength(30);
            entity.Property(e => e.IndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ItmCod).HasMaxLength(30);
            entity.Property(e => e.ItmDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdCod).HasMaxLength(30);
            entity.Property(e => e.JobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdUid).HasMaxLength(30);
            entity.Property(e => e.LotCod).HasMaxLength(30);
            entity.Property(e => e.PhaCod).HasMaxLength(30);
            entity.Property(e => e.PhaCycCod).HasMaxLength(13);
            entity.Property(e => e.PhaPhsCod).HasMaxLength(3);
            entity.Property(e => e.PrdCycCod).HasMaxLength(30);
            entity.Property(e => e.PrdOrdCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsDsc).HasMaxLength(100);
            entity.Property(e => e.PrjCod).HasMaxLength(30);
            entity.Property(e => e.PrjDsc).HasMaxLength(100);
            entity.Property(e => e.PrjTskUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.PrjUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ProCod).HasMaxLength(30);
            entity.Property(e => e.PrsFld001).HasMaxLength(30);
            entity.Property(e => e.PrsFld002).HasMaxLength(30);
            entity.Property(e => e.PrsFld003).HasMaxLength(30);
            entity.Property(e => e.PrsFld004).HasMaxLength(30);
            entity.Property(e => e.PrsFld005).HasMaxLength(30);
            entity.Property(e => e.PrsFld006).HasMaxLength(30);
            entity.Property(e => e.PrsFld007).HasMaxLength(30);
            entity.Property(e => e.PrsFld008).HasMaxLength(30);
            entity.Property(e => e.PrsFld009).HasMaxLength(30);
            entity.Property(e => e.PrsFld010).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr001).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr002).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr003).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr004).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr005).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr006).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr007).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr008).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr009).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr010).HasMaxLength(30);
            entity.Property(e => e.PrsFldIco001).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco002).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco003).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco004).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco005).HasMaxLength(50);
            entity.Property(e => e.PrtNum).HasColumnType("decimal(7, 0)");
            entity.Property(e => e.Qt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Ord).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Res).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyMin).HasColumnType("decimal(17, 7)");
            entity.Property(e => e.QtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyOrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPhsPrv).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRes).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.RefCod).HasMaxLength(30);
            entity.Property(e => e.ResCod).HasMaxLength(20);
            entity.Property(e => e.SubJobOrdCod).HasMaxLength(30);
            entity.Property(e => e.SubJobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.SubJobOrdUid).HasMaxLength(30);
            entity.Property(e => e.TotWrkTim).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
            entity.Property(e => e.UniMeaBasCod).HasMaxLength(2);
            entity.Property(e => e.WrcCod).HasMaxLength(30);
            entity.Property(e => e.WrcDsc).HasMaxLength(100);
            entity.Property(e => e.WrcUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.WrkTimOpe).HasColumnType("decimal(17, 4)");

            entity.HasOne(d => d.DecTypU).WithMany(p => p.MesBckEvtDet)
                .HasForeignKey(d => d.DecTypUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00062");

            entity.HasOne(d => d.EvtDetRefU).WithMany(p => p.InverseEvtDetRefU)
                .HasForeignKey(d => d.EvtDetRefUid)
                .HasConstraintName("FMes00063");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesBckEvtDet)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00061");
        });

        modelBuilder.Entity<MesBckEvtMacDet>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesBckEv__C5B69A4A9F3E8292");

            entity.HasIndex(e => new { e.EvtUid, e.EvtDetUid }, "IDXCODE329");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DecAdv).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DivQt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivTim).HasColumnType("decimal(13, 4)");
            entity.Property(e => e.EvtDetUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtMovUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.MovPrv).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.NmvQt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.PerCom).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.Qt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPhsPrv).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.EvtDetU).WithMany(p => p.MesBckEvtMacDet)
                .HasForeignKey(d => d.EvtDetUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00067");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesBckEvtMacDet)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00066");
        });

        modelBuilder.Entity<MesBckEvtOpe>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesBckEv__C5B69A4A377AFA34");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BasTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.MacSftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SspUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.StsUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.TssEnd).HasColumnType("datetime");
            entity.Property(e => e.TssStr).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.BrkU).WithMany(p => p.MesBckEvtOpe)
                .HasForeignKey(d => d.BrkUid)
                .HasConstraintName("FMes00065");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesBckEvtOpe)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00058");

            entity.HasOne(d => d.ResU).WithMany(p => p.MesBckEvtOpe)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00059");

            entity.HasOne(d => d.SspU).WithMany(p => p.MesBckEvtOpe)
                .HasForeignKey(d => d.SspUid)
                .HasConstraintName("FMes00051");

            entity.HasOne(d => d.StsU).WithMany(p => p.MesBckEvtOpe)
                .HasForeignKey(d => d.StsUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00064");
        });

        modelBuilder.Entity<MesDiaDefMac>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesDiaDe__C5B69A4A25D66F67");

            entity.HasIndex(e => new { e.ResUid, e.MacUid }, "IDXCODE247");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.MacSrtOrd).HasColumnType("decimal(4, 0)");
            entity.Property(e => e.MacUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.MacU).WithMany(p => p.MesDiaDefMacMacU)
                .HasForeignKey(d => d.MacUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00027");

            entity.HasOne(d => d.ResU).WithMany(p => p.MesDiaDefMacResU)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00026");
        });

        modelBuilder.Entity<MesDiaOpe>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesDiaOp__C5B69A4A761E262A");

            entity.HasIndex(e => new { e.ResPriUid, e.ActPri }, "MesEvtIx1");

            entity.HasIndex(e => new { e.ResPriUid, e.ResLgnUid }, "MesEvtIx5");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ActPri).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.CnlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.OrgLvlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResLgnUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResNot).HasMaxLength(1000);
            entity.Property(e => e.ResPriUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SevUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SspUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.StsUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesDiaOpe)
                .HasForeignKey(d => d.EvtUid)
                .HasConstraintName("FMes00015");

            entity.HasOne(d => d.ResLgnU).WithMany(p => p.MesDiaOpeResLgnU)
                .HasForeignKey(d => d.ResLgnUid)
                .HasConstraintName("FMes00014");

            entity.HasOne(d => d.ResPriU).WithMany(p => p.MesDiaOpeResPriU)
                .HasForeignKey(d => d.ResPriUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00013");

            entity.HasOne(d => d.SspU).WithMany(p => p.MesDiaOpe)
                .HasForeignKey(d => d.SspUid)
                .HasConstraintName("FMes00033");

            entity.HasOne(d => d.StsU).WithMany(p => p.MesDiaOpe)
                .HasForeignKey(d => d.StsUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00016");
        });

        modelBuilder.Entity<MesDiaOpeDet>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesDiaOp__C5B69A4A443042E2");

            entity.HasIndex(e => new { e.DiaOpeUid, e.DecTypUid, e.DocCod }, "IDXCODE315");

            entity.HasIndex(e => e.DocPri, "MesEvtIx4");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CauCod).HasMaxLength(30);
            entity.Property(e => e.CusCod).HasMaxLength(30);
            entity.Property(e => e.CusDsc).HasMaxLength(100);
            entity.Property(e => e.DecTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DiaOpeDetRefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DiaOpeUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DocCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.DocPri).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DptCod).HasMaxLength(30);
            entity.Property(e => e.DrwCod).HasMaxLength(20);
            entity.Property(e => e.EqpCod).HasMaxLength(20);
            entity.Property(e => e.ExtCod).HasMaxLength(30);
            entity.Property(e => e.IndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ItmCod).HasMaxLength(30);
            entity.Property(e => e.ItmDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdCod).HasMaxLength(30);
            entity.Property(e => e.JobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdUid).HasMaxLength(30);
            entity.Property(e => e.LotCod).HasMaxLength(30);
            entity.Property(e => e.PrdCycCod).HasMaxLength(30);
            entity.Property(e => e.PrdOrdCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsDsc).HasMaxLength(100);
            entity.Property(e => e.PrjCod).HasMaxLength(30);
            entity.Property(e => e.PrjDsc).HasMaxLength(100);
            entity.Property(e => e.PrsFld001).HasMaxLength(30);
            entity.Property(e => e.PrsFld002).HasMaxLength(30);
            entity.Property(e => e.PrsFld003).HasMaxLength(30);
            entity.Property(e => e.PrsFld004).HasMaxLength(30);
            entity.Property(e => e.PrsFld005).HasMaxLength(30);
            entity.Property(e => e.PrsFld006).HasMaxLength(30);
            entity.Property(e => e.PrsFld007).HasMaxLength(30);
            entity.Property(e => e.PrsFld008).HasMaxLength(30);
            entity.Property(e => e.PrsFld009).HasMaxLength(30);
            entity.Property(e => e.PrsFld010).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr001).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr002).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr003).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr004).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr005).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr006).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr007).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr008).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr009).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr010).HasMaxLength(30);
            entity.Property(e => e.PrsFldIco001).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco002).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco003).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco004).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco005).HasMaxLength(50);
            entity.Property(e => e.PrtNum).HasColumnType("decimal(7, 0)");
            entity.Property(e => e.Qt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Ord).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Res).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyOrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPhsPrv).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRes).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.RefCod).HasMaxLength(30);
            entity.Property(e => e.ResCod).HasMaxLength(20);
            entity.Property(e => e.SubJobOrdCod).HasMaxLength(30);
            entity.Property(e => e.SubJobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.SubJobOrdUid).HasMaxLength(30);
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
            entity.Property(e => e.UniMeaBasCod).HasMaxLength(2);
            entity.Property(e => e.WrcCod).HasMaxLength(30);
            entity.Property(e => e.WrcDsc).HasMaxLength(100);
            entity.Property(e => e.WrcUid).HasColumnType("decimal(10, 0)");

            entity.HasOne(d => d.DecTypU).WithMany(p => p.MesDiaOpeDet)
                .HasForeignKey(d => d.DecTypUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00024");

            entity.HasOne(d => d.DiaOpeDetRefU).WithMany(p => p.InverseDiaOpeDetRefU)
                .HasForeignKey(d => d.DiaOpeDetRefUid)
                .HasConstraintName("FMes00025");

            entity.HasOne(d => d.DiaOpeU).WithMany(p => p.MesDiaOpeDet)
                .HasForeignKey(d => d.DiaOpeUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00023");
        });

        modelBuilder.Entity<MesEvt>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesEvt__C5B69A4A9130E418");

            entity.HasIndex(e => new { e.ResPriUid, e.EvtTypUid, e.TssEnd }, "MesEvtIx2");

            entity.HasIndex(e => e.EvtRefUid, "MesEvtIx6");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CnlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DtcDayUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtAnmUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtChk).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.EvtPerEff).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.EvtRefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUac).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MatDecLck).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MatFlg).HasMaxLength(20);
            entity.Property(e => e.OrgLvlUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.OvrLapNum).HasColumnType("decimal(20, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResEffEndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResEffStrUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResLgnEndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResLgnStrUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResOrgUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResPriUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SspUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.TssCnsQty).HasColumnType("datetime");
            entity.Property(e => e.TssCnsTim).HasColumnType("datetime");
            entity.Property(e => e.TssEnd).HasColumnType("datetime");
            entity.Property(e => e.TssStr).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.DtcDayU).WithMany(p => p.MesEvt)
                .HasForeignKey(d => d.DtcDayUid)
                .HasConstraintName("FMes00039");

            entity.HasOne(d => d.ResEffEndU).WithMany(p => p.MesEvtResEffEndU)
                .HasForeignKey(d => d.ResEffEndUid)
                .HasConstraintName("FMes00012");

            entity.HasOne(d => d.ResEffStrU).WithMany(p => p.MesEvtResEffStrU)
                .HasForeignKey(d => d.ResEffStrUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00011");

            entity.HasOne(d => d.ResLgnEndU).WithMany(p => p.MesEvtResLgnEndU)
                .HasForeignKey(d => d.ResLgnEndUid)
                .HasConstraintName("FMes00010");

            entity.HasOne(d => d.ResLgnStrU).WithMany(p => p.MesEvtResLgnStrU)
                .HasForeignKey(d => d.ResLgnStrUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00009");

            entity.HasOne(d => d.ResOr).WithMany(p => p.MesEvtResOr)
                .HasForeignKey(d => d.ResOrgUid)
                .HasConstraintName("FMes00041");

            entity.HasOne(d => d.ResPriU).WithMany(p => p.MesEvtResPriU)
                .HasForeignKey(d => d.ResPriUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00007");

            entity.HasOne(d => d.SspU).WithMany(p => p.MesEvt)
                .HasForeignKey(d => d.SspUid)
                .HasConstraintName("FMes00032");
        });

        modelBuilder.Entity<MesEvtDet>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesEvtDe__C5B69A4AB39F9631");

            entity.ToTable(tb => tb.HasTrigger("GBPM_7_I"));

            entity.HasIndex(e => new { e.EvtUid, e.DecTypUid, e.DocCod }, "IDXCODE314");

            entity.HasIndex(e => new { e.EvtUid, e.DocPri }, "MesEvtIx3");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.CauCod).HasMaxLength(30);
            entity.Property(e => e.CusCod).HasMaxLength(30);
            entity.Property(e => e.CusDsc).HasMaxLength(100);
            entity.Property(e => e.DecTypUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DocCod)
                .IsRequired()
                .HasMaxLength(30);
            entity.Property(e => e.DocPri).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DptCod).HasMaxLength(30);
            entity.Property(e => e.DrwCod).HasMaxLength(20);
            entity.Property(e => e.EqpCod).HasMaxLength(20);
            entity.Property(e => e.EvtDetRefUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ExtCod).HasMaxLength(30);
            entity.Property(e => e.IndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ItmCod).HasMaxLength(30);
            entity.Property(e => e.ItmDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdCod).HasMaxLength(30);
            entity.Property(e => e.JobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.JobOrdUid).HasMaxLength(30);
            entity.Property(e => e.LotCod).HasMaxLength(30);
            entity.Property(e => e.PhaCod).HasMaxLength(30);
            entity.Property(e => e.PhaCycCod).HasMaxLength(13);
            entity.Property(e => e.PhaPhsCod).HasMaxLength(3);
            entity.Property(e => e.PrdCycCod).HasMaxLength(30);
            entity.Property(e => e.PrdOrdCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsCod).HasMaxLength(30);
            entity.Property(e => e.PrdPhsDsc).HasMaxLength(100);
            entity.Property(e => e.PrjCod).HasMaxLength(30);
            entity.Property(e => e.PrjDsc).HasMaxLength(100);
            entity.Property(e => e.PrjTskUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.PrjUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ProCod).HasMaxLength(30);
            entity.Property(e => e.PrsFld001).HasMaxLength(30);
            entity.Property(e => e.PrsFld002).HasMaxLength(30);
            entity.Property(e => e.PrsFld003).HasMaxLength(30);
            entity.Property(e => e.PrsFld004).HasMaxLength(30);
            entity.Property(e => e.PrsFld005).HasMaxLength(30);
            entity.Property(e => e.PrsFld006).HasMaxLength(30);
            entity.Property(e => e.PrsFld007).HasMaxLength(30);
            entity.Property(e => e.PrsFld008).HasMaxLength(30);
            entity.Property(e => e.PrsFld009).HasMaxLength(30);
            entity.Property(e => e.PrsFld010).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr001).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr002).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr003).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr004).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr005).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr006).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr007).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr008).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr009).HasMaxLength(30);
            entity.Property(e => e.PrsFldClr010).HasMaxLength(30);
            entity.Property(e => e.PrsFldIco001).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco002).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco003).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco004).HasMaxLength(50);
            entity.Property(e => e.PrsFldIco005).HasMaxLength(50);
            entity.Property(e => e.PrtNum).HasColumnType("decimal(7, 0)");
            entity.Property(e => e.Qt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Ord).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Res).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyMin).HasColumnType("decimal(17, 7)");
            entity.Property(e => e.QtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyOrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPhsPrv).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRes).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.RefCod).HasMaxLength(30);
            entity.Property(e => e.ResCod).HasMaxLength(20);
            entity.Property(e => e.SubJobOrdCod).HasMaxLength(30);
            entity.Property(e => e.SubJobOrdDsc).HasMaxLength(100);
            entity.Property(e => e.SubJobOrdUid).HasMaxLength(30);
            entity.Property(e => e.TotWrkTim).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");
            entity.Property(e => e.UniMeaBasCod).HasMaxLength(2);
            entity.Property(e => e.WrcCod).HasMaxLength(30);
            entity.Property(e => e.WrcDsc).HasMaxLength(100);
            entity.Property(e => e.WrcUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.WrkTimOpe).HasColumnType("decimal(17, 4)");

            entity.HasOne(d => d.DecTypU).WithMany(p => p.MesEvtDet)
                .HasForeignKey(d => d.DecTypUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00021");

            entity.HasOne(d => d.EvtDetRefU).WithMany(p => p.InverseEvtDetRefU)
                .HasForeignKey(d => d.EvtDetRefUid)
                .HasConstraintName("FMes00022");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesEvtDet)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00020");
        });

        modelBuilder.Entity<MesEvtMacDet>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesEvtMa__C5B69A4A52F765E3");

            entity.HasIndex(e => new { e.EvtUid, e.EvtDetUid }, "IDXCODE318");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DecAdv).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.DivQt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivQtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.DivTim).HasColumnType("decimal(13, 4)");
            entity.Property(e => e.EvtDetUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtMovUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.MovPrv).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.NmvQt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.NmvQtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.PerCom).HasColumnType("decimal(7, 2)");
            entity.Property(e => e.Qt2Nco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Prd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.Qt2Rej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyNco).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPhsPrv).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyPrd).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.QtyRej).HasColumnType("decimal(17, 4)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.EvtDetU).WithMany(p => p.MesEvtMacDet)
                .HasForeignKey(d => d.EvtDetUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00029");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesEvtMacDet)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00028");
        });

        modelBuilder.Entity<MesEvtOpe>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__MesEvtOp__C5B69A4ACB0BE3A8");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BasTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.MacSftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SspUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.StsUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.TssEnd).HasColumnType("datetime");
            entity.Property(e => e.TssStr).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.BrkU).WithMany(p => p.MesEvtOpe)
                .HasForeignKey(d => d.BrkUid)
                .HasConstraintName("FMes00027");

            entity.HasOne(d => d.EvtU).WithMany(p => p.MesEvtOpe)
                .HasForeignKey(d => d.EvtUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00017");

            entity.HasOne(d => d.ResU).WithMany(p => p.MesEvtOpe)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00018");

            entity.HasOne(d => d.SspU).WithMany(p => p.MesEvtOpe)
                .HasForeignKey(d => d.SspUid)
                .HasConstraintName("FMes00001");

            entity.HasOne(d => d.StsU).WithMany(p => p.MesEvtOpe)
                .HasForeignKey(d => d.StsUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00026");
        });

        modelBuilder.Entity<TblMesClkRes>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__TblMesCl__C5B69A4AE335773D");

            entity.HasIndex(e => new { e.ResUid, e.EvtUid }, "IDXCODE322");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BasTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EvtUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.LogDel).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.MacSftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.SftTeaUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsd).HasColumnType("datetime");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.ResU).WithMany(p => p.TblMesClkRes)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FMes00036");
        });

        modelBuilder.Entity<TblResBrk>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__TblResBr__C5B69A4A0B478EC6");

            entity.HasIndex(e => new { e.ResUid, e.TssStr }, "IDXCODE243");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.BrkUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.DtcDayUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EdtTssEnd).HasColumnType("datetime");
            entity.Property(e => e.EdtTssStr).HasColumnType("datetime");
            entity.Property(e => e.EtyUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResLgnEndUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResLgnStrUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.TssEnd).HasColumnType("datetime");
            entity.Property(e => e.TssStr).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.BrkU).WithMany(p => p.TblResBrk)
                .HasForeignKey(d => d.BrkUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00019");

            entity.HasOne(d => d.DtcDayU).WithMany(p => p.TblResBrk)
                .HasForeignKey(d => d.DtcDayUid)
                .HasConstraintName("FRes00030");

            entity.HasOne(d => d.ResLgnEndU).WithMany(p => p.TblResBrkResLgnEndU)
                .HasForeignKey(d => d.ResLgnEndUid)
                .HasConstraintName("FRes00017");

            entity.HasOne(d => d.ResLgnStrU).WithMany(p => p.TblResBrkResLgnStrU)
                .HasForeignKey(d => d.ResLgnStrUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00016");

            entity.HasOne(d => d.ResU).WithMany(p => p.TblResBrkResU)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00018");
        });

        modelBuilder.Entity<TblResClk>(entity =>
        {
            entity.HasKey(e => e.Uid).HasName("PK__TblResCl__C5B69A4A3F145D66");

            entity.Property(e => e.Uid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.AbsClk).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.ClkInnTss).HasColumnType("datetime");
            entity.Property(e => e.ClkOutTss).HasColumnType("datetime");
            entity.Property(e => e.DtcDayUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EdtInnRngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EdtInnTss).HasColumnType("datetime");
            entity.Property(e => e.EdtOutRngUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.EdtOutTss).HasColumnType("datetime");
            entity.Property(e => e.FlgFrcClk).HasColumnType("decimal(1, 0)");
            entity.Property(e => e.KpiRngInnUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.RecVer).HasColumnType("decimal(5, 0)");
            entity.Property(e => e.ResUid).HasColumnType("decimal(10, 0)");
            entity.Property(e => e.Tsi).HasColumnType("datetime");
            entity.Property(e => e.Tsu).HasColumnType("datetime");

            entity.HasOne(d => d.DtcDayU).WithMany(p => p.TblResClk)
                .HasForeignKey(d => d.DtcDayUid)
                .HasConstraintName("FRes00028");

            entity.HasOne(d => d.ResU).WithMany(p => p.TblResClk)
                .HasForeignKey(d => d.ResUid)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FRes00013");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}